In [1]:
import pandas as pd

# Assuming your CSV file is named 'your_file.csv'
#df = pd.read_csv('AD4_14_59_36.csv', delimiter=',')
df = pd.read_csv('SMINA_12_28_10.csv', delimiter=',')
#df = pd.read_csv('VINA_11_22_02.csv', delimiter=',')
print(df)
# Extract the ligand names and energies
df['Ligand'] = df['Ligand Name'].apply(lambda x: x.split('_')[1])
df['Energy'] = pd.to_numeric(df['Energy'])  # Convert 'Energy' column to numeric values

# Calculate the mean energy for each ligand
mean_energy_df = df.groupby('Ligand')['Energy'].mean().reset_index()

# Sort the dataframe by mean energy in ascending order
mean_energy_df = mean_energy_df.sort_values(by='Energy')

# Display the resulting dataframe
print(mean_energy_df)

      Unnamed: 0                           Ligand Name     Energy    LogP  \
0              0   output52_ligand419_2023-11-22-15:52 -10.721047 -5.2014
1              1  output413_ligand369_2023-11-22-15:52 -10.572432  6.4646
2              2  output413_ligand422_2023-11-22-15:52 -10.414018  1.3872
3              3   output44_ligand421_2023-11-22-15:52 -10.268977  0.0582
4              4   output44_ligand217_2023-11-22-15:52 -10.258236  1.0990
...          ...                                   ...        ...     ...
5917        5917  output417_ligand724_2023-11-22-15:52  -3.093379 -3.7094
5918        5918   output52_ligand724_2023-11-22-15:52  -3.034424 -3.7094
5919        5919   output44_ligand724_2023-11-22-15:52  -3.023925 -3.7094
5920        5920  output413_ligand724_2023-11-22-15:52  -2.956891 -3.7094
5921        5921   output12_ligand724_2023-11-22-15:52  -2.847260 -3.7094

           MolWt    Complexity                         Center of mass
0     894.446045  1.207159e+00  [31.83609141 48.20319051 30.11541056]
1     443.322186  1.274919e+00  [32.45335344 45.466273   27.86242229]
2     603.435970  1.017999e+00  [35.39086772 46.42381759 27.32160469]
3     603.453100  1.150603e+00  [34.15016223 46.31790059 27.66744228]
4     591.435970  1.152265e+00  [34.35768193 45.73515205 27.56357107]
...          ...           ...                                    ...
5917   86.178072 -8.333333e-10  [24.76469478 38.5992509  26.67629937]
5918   86.178072 -8.333333e-10  [25.98678093 38.43321914 26.92458171]
5919   86.178072 -8.333333e-10  [30.11986865 38.262557   23.67533778]
5920   86.178072 -8.333333e-10  [26.48468369 37.87477747 26.20713862]
5921   86.178072 -8.333333e-10  [26.23200021 38.39230756 26.98358939]

[5922 rows x 7 columns]
        Ligand    Energy
353  ligand420 -9.463563
355  ligand422 -9.103317
351  ligand419 -9.098691
308  ligand379 -9.046568
297  ligand369 -9.004200
..         ...       ...
871  ligand895 -3.817120
686  ligand722 -3.768394
791  ligand822 -3.671535
981  ligand994 -3.492129
688  ligand724 -3.037153

[987 rows x 2 columns]

In [15]:
mean_energy_df.reset_index()

     index     Ligand    Energy
0      353  ligand420 -9.463563
1      355  ligand422 -9.103317
2      351  ligand419 -9.098691
3      308  ligand379 -9.046568
4      297  ligand369 -9.004200
..     ...        ...       ...
982    871  ligand895 -3.817120
983    686  ligand722 -3.768394
984    791  ligand822 -3.671535
985    981  ligand994 -3.492129
986    688  ligand724 -3.037153

[987 rows x 3 columns]

In [16]:
mean_energy_df.head(10)

        Ligand    Energy
353  ligand420 -9.463563
355  ligand422 -9.103317
351  ligand419 -9.098691
308  ligand379 -9.046568
297  ligand369 -9.004200
292  ligand364 -8.881291
209  ligand289 -8.839654
603  ligand646 -8.768167
354  ligand421 -8.570295
317  ligand387 -8.551740

In [24]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Assuming your CSV file is named 'your_file.csv'
df = pd.read_csv('SMINA_12_28_10.csv', delimiter=',')
print(df)

# Extract the ligand names and energies
df['Ligand'] = df['Ligand Name'].apply(lambda x: x.split('_')[1])
df['Energy'] = pd.to_numeric(df['Energy'])  # Convert 'Energy' column to numeric values

# Filter out rows where MolWt is approximately equal to 0
df = df[df['Complexity'] != 0]

# Calculate the mean energy and mean MolWt for each ligand
mean_energy_df = df.groupby('Ligand').agg({'Energy': 'mean', 'Complexity': 'mean'}).reset_index()

# Sort the dataframe by mean energy in ascending order
mean_energy_df = mean_energy_df.sort_values(by='Energy')

# Set seaborn style
sns.set(style="whitegrid")

# Create a scatter plot using seaborn
plt.figure(figsize=(10, 6))
sns.scatterplot(x='Energy', y='Complexity', data=mean_energy_df, palette='viridis', edgecolor='w', s=100)

# Add labels and title
plt.xlabel('Mean Energy')
plt.ylabel('Complexity')
plt.title('Complexity in function of Mean Energy')

# Show the plot
plt.show()

      Unnamed: 0                           Ligand Name     Energy    LogP  \
0              0   output52_ligand419_2023-11-22-15:52 -10.721047 -5.2014
1              1  output413_ligand369_2023-11-22-15:52 -10.572432  6.4646
2              2  output413_ligand422_2023-11-22-15:52 -10.414018  1.3872
3              3   output44_ligand421_2023-11-22-15:52 -10.268977  0.0582
4              4   output44_ligand217_2023-11-22-15:52 -10.258236  1.0990
...          ...                                   ...        ...     ...
5917        5917  output417_ligand724_2023-11-22-15:52  -3.093379 -3.7094
5918        5918   output52_ligand724_2023-11-22-15:52  -3.034424 -3.7094
5919        5919   output44_ligand724_2023-11-22-15:52  -3.023925 -3.7094
5920        5920  output413_ligand724_2023-11-22-15:52  -2.956891 -3.7094
5921        5921   output12_ligand724_2023-11-22-15:52  -2.847260 -3.7094

           MolWt    Complexity                         Center of mass
0     894.446045  1.207159e+00  [31.83609141 48.20319051 30.11541056]
1     443.322186  1.274919e+00  [32.45335344 45.466273   27.86242229]
2     603.435970  1.017999e+00  [35.39086772 46.42381759 27.32160469]
3     603.453100  1.150603e+00  [34.15016223 46.31790059 27.66744228]
4     591.435970  1.152265e+00  [34.35768193 45.73515205 27.56357107]
...          ...           ...                                    ...
5917   86.178072 -8.333333e-10  [24.76469478 38.5992509  26.67629937]
5918   86.178072 -8.333333e-10  [25.98678093 38.43321914 26.92458171]
5919   86.178072 -8.333333e-10  [30.11986865 38.262557   23.67533778]
5920   86.178072 -8.333333e-10  [26.48468369 37.87477747 26.20713862]
5921   86.178072 -8.333333e-10  [26.23200021 38.39230756 26.98358939]

[5922 rows x 7 columns]

In [28]:
import pandas as pd

# Assuming your CSV file is named 'your_file.csv'
df = pd.read_csv('VINA_11_22_02.csv', delimiter=',')
print(df)

# Extract the ligand names and energies
df['Receptor'] = df['Ligand Name'].apply(lambda x: x.split('_')[0])
df['Energy'] = pd.to_numeric(df['Energy'])  # Convert 'Energy' column to numeric values

# Calculate the mean energy for each receptor
mean_energy_receptor_df = df.groupby('Receptor')['Energy'].mean().reset_index()

# Sort the dataframe by mean energy in ascending order
mean_energy_receptor_df = mean_energy_receptor_df.sort_values(by='Energy')

# Display the resulting dataframe
mean_energy_receptor_df.head(10)

      Unnamed: 0                           Ligand Name  Energy    LogP  \
0              0  output413_ligand369_2023-11-21-14:35 -10.578  6.4646
1              1  output413_ligand422_2023-11-21-14:35 -10.191  1.3872
2              2   output44_ligand217_2023-11-21-14:35 -10.119  1.0990
3              3   output44_ligand421_2023-11-21-14:35  -9.883  0.0582
4              4   output52_ligand375_2023-11-21-14:35  -9.872  4.5489
...          ...                                   ...     ...     ...
5916        5916   output52_ligand724_2023-11-21-14:35  -3.253 -3.7094
5917        5917  output417_ligand724_2023-11-21-14:35  -3.092 -3.7094
5918        5918   output44_ligand724_2023-11-21-14:35  -3.004 -3.7094
5919        5919  output413_ligand724_2023-11-21-14:35  -2.944 -3.7094
5920        5920   output12_ligand724_2023-11-21-14:35  -2.744 -3.7094

           MolWt    Complexity                         Center of mass
0     443.322186  1.274919e+00  [32.43858348 45.44542865 27.89059798]
1     603.435970  1.017999e+00  [35.44770967 46.4085053  27.35491535]
2     591.435970  1.152265e+00  [34.40206921 45.98633045 27.70563463]
3     603.453100  1.150603e+00  [34.07121165 46.38276474 27.76697591]
4     548.418923  1.091928e+00  [28.55371621 46.66988528 33.04687761]
...          ...           ...                                    ...
5916   86.178072 -8.333333e-10  [32.21457719 29.58770258 24.41599198]
5917   86.178072 -8.333333e-10  [24.77596022 38.59015092 26.65929654]
5918   86.178072 -8.333333e-10  [30.12081113 38.23968899 23.68598507]
5919   86.178072 -8.333333e-10  [26.50368525 37.8468338  26.28776712]
5920   86.178072 -8.333333e-10  [26.25620942 38.53138611 26.61885535]

[5921 rows x 7 columns]

    Receptor    Energy
5   output52 -7.196098
4   output44 -7.134180
1   output26 -6.896758
2  output413 -6.690353
3  output417 -6.536440
0   output12 -6.396806